seed = 0
n_clusters = 20
eplison = 0.1
max_iter = 200
weight_ = 0.5

[data]
normalization = "quantile"
path = "data/jannis"

[model]
d_layers = [ 256, 256, 256,]
dropout = 0.1
d_embedding = 128

[training]
batch_size = 128
eval_batch_size = 8192
lr = 0.0001
n_epochs = 1000000000
optimizer = "adamw"
patience = 20
weight_decay = 1e-5
